export const productDetailContent = {
  de: {
    sicherungsschaltgeraete: {
      models: [
        { id: 'tytan-i', name: 'TYTAN® I', tagline: 'Universeller Sicherungsstecker', desc: 'Universeller Sicherungsstecker mit integriertem Blinkmelder. Kompatibel mit Leitungsschutzschaltern. Plombierbar.', pdf: '/pdfs/tytan_I_datasheet_katalog.pdf', tag: 'Beliebt' },
        { id: 'tytan-ii', name: 'TYTAN® II', tagline: 'Vollcodierter Schutz', desc: 'Vollcodierung für 1 bis 63 A mit lückenlosen Zwischenstufen (13, 32, 40 A). Blinkmelder direkt im Stecker integriert.', pdf: '/pdfs/tytan_II_datasheet_katalog-neu2.pdf', tag: 'Flaggschiff' },
        { id: 'tytan-t', name: 'TYTAN® T', tagline: 'Kompaktgerät mit 4 TE', desc: 'Bauform mit 4 TE Breite und optionalen Überwachungsfunktionen. Lasttrennschalter für mehrere Sicherungstypen.', pdf: '/pdfs/tytan_T_datasheet_katalog-neu.pdf', tag: null },
        { id: 'tytan-t4p', name: 'TYTAN® T4P', tagline: 'Mehrfach-Sicherungslastschalter', desc: 'Lasttrennschalter für D0 1 / D0 2 / D0 3 Sicherungen in einem kompakten 4-TE-Gerät.', pdf: '/pdfs/tytan_T4p_datasheet_katalog.pdf', tag: null },
        { id: 'tytan-t4h', name: 'TYTAN® T4H/T4HP/T4HR', tagline: 'Phasenüberwachung', desc: 'Kompakte 4-TE-Breite mit integrierter Drehfeld- und Phasenausfallüberwachung.', pdf: '/pdfs/t4h_p_r_datasheet_katalog.pdf', tag: null },
        { id: 'tytan-th1', name: 'TYTAN® TH1', tagline: 'Sicherung plus Temperatur', desc: 'Kombiniert Sicherungsschutz mit integrierter Temperaturüberwachung zur frühzeitigen Überlasterkennung.', pdf: '/pdfs/th1_datasheet_katalog.pdf', tag: null },
        { id: 'tytan-thbus', name: 'TYTAN® THBus', tagline: 'Modbus-RTU-Schnittstelle', desc: 'Überwacht bis zu 28 Geräte gleichzeitig via Modbus RTU, ideal für die Integration in smarte Gebäude.', pdf: '/pdfs/thbus_datasheet_katalog.pdf', tag: 'Smart' },
        { id: 'coron-duo', name: 'CORON® DUO', tagline: '27 mm pro Pol', desc: '27 mm Breite pro Pol mit Option auf integrierten Hilfsschalter. Modulares und platzsparendes Design.', pdf: '/pdfs/coron_duo_datasheet_katalog-neu.pdf', tag: null },
        { id: 'coron-2', name: 'CORON® 2', tagline: 'Plombieren und verriegeln', desc: 'Plombierbar und mit Vorhängeschloss verriegelbar. Maximaler Schutz gegen unbefugten Zugriff.', pdf: '/pdfs/coron_2_datasheet_katalog.pdf', tag: null },
        { id: 'in-on', name: 'IN-ON', tagline: 'Tasterauslösung', desc: 'Plombier- und verriegelbar mit Tasterauslösung. Einfache und sichere Bedienung für industrielle Anwendungen.', pdf: '/pdfs/in-on_datasheet_katalog-update.pdf', tag: null },
      ],
      specs: [
        { key: 'Produktreihen', value: 'TYTAN®, CORON®, IN-ON' },
        { key: 'Nennstrom', value: 'bis 100 A' },
        { key: 'Nennspannung', value: 'bis 690 V AC' },
        { key: 'Sicherungstypen', value: 'D0 1, D0 2, D0 3' },
        { key: 'Schutzart', value: 'IP20' },
        { key: 'Montage', value: 'Hutschiene EN 60715' },
        { key: 'Temperaturbereich', value: '-25 °C bis +55 °C' },
        { key: 'Zertifizierung', value: 'CE, VDE, EN 60269' },
      ],
      heroLabel: 'TYTAN® · CORON® · IN-ON',
      heroTitle1: 'Sicherungsschalt',
      heroTitle2: 'geräte',
      heroDesc: 'Professionelle Sicherungslasttrennschalter für Hutschienen mit Blinkmelder, Messstecker und Temperaturüberwachung. Klaus Bruchmann GmbH, seit 1985.',
      breadcrumbCurrent: 'Sicherungsschaltgeräte',
      badges: ['ISO 9001', 'ISO 14001', 'CE / VDE', 'Made in Germany'],
      stats: [{ v: '10+', l: 'Produktmodelle' }, { v: '100A', l: 'Max. Nennstrom' }, { v: '690V', l: 'Max. Nennspannung' }, { v: '1985', l: 'Gründungsjahr' }],
      rangeTitle: 'TYTAN® & CORON® Serien',
      rangeSub: '10 Spezialmodelle vom Basisschutz bis zur intelligenten Modbus-Überwachung.',
      explorerBody: 'Betrachten Sie das Sicherungsschaltgerät aus jedem Winkel. Drehen, zoomen und verschieben Sie das Modell für einen genauen Blick auf die Konstruktion.',
      viewerBadge: 'TYTAN® Sicherungsschaltgerät',
      specsSub: 'Parameter über die gesamte TYTAN®- und CORON®-Familie hinweg. Modellspezifische Werte finden Sie in den jeweiligen Datenblättern.',
      imageAlt: 'Sicherungsschaltgerät',
      ctaTitle: 'Interesse an Sicherungsschaltgeräten?',
      certLabel: 'ISO 9001 · ISO 14001 zertifiziert',
    },
    hauptschutz: {
      models: [
        { id: 'tytan-ii-hs', name: 'TYTAN® II', tagline: 'Vollcodierter Hauptschutz', desc: 'Blinkmelder im Stecker, Vollcodierung für alle Stromstärken. Plombierbare und abschließbare Bauweise für maximale Sicherheit.', pdf: '/pdfs/tytanII_hs_datasheet_katalog-neu-1.pdf', tag: 'Flaggschiff' },
        { id: 'tytan-ii-adapter', name: 'TYTAN® II Geräteadapter', tagline: '2-polig und 3-polig', desc: '2-polig 81 mm / 3-polig 108 mm. Montage auf 60-mm-Systemadaptern für Kupferleiter von 12 bis 30 mm Breite.', pdf: '/pdfs/tytanII_geraeteadapter_hs_datasheet_katalog-update_2.pdf', tag: null },
        { id: 'tytan-t4h-hs', name: 'TYTAN® T4H / T4HP / T4HR', tagline: 'Mehrphasenüberwachung', desc: 'Kompakte 4-TE-Breite. Potenzialfreier Wechsler für die Sicherungsüberwachung von L1, L2, L3. Inklusive Blinkmelder und Universalstecker.', pdf: '/pdfs/t4h_p_r_datasheet_katalog-1.pdf', tag: null },
        { id: 'tytan-rh4', name: 'TYTAN® RH4', tagline: 'Selbstversorgter Melder', desc: 'Blinkmelder in selbstversorgter Ausführung. 36 mm / 2 TE breit, abschließbares Gehäuse mit Sicherungsstecker, ohne Hilfsspannung nutzbar.', pdf: '/pdfs/rh4_datasheet_katalog-update.pdf', tag: null },
        { id: 'tytan-rh1', name: 'TYTAN® RH1 Hauptschutz', tagline: 'Sicherungs- und Temperaturüberwachung', desc: 'Kombiniert Sicherungs- und Temperaturüberwachung mit potenzialfreien Relaiskontakten für die direkte Einbindung in Gebäudemanagementsysteme.', pdf: '/pdfs/rh1_datasheet_katalog-update.pdf', tag: null },
        { id: 'tytan-th1', name: 'TYTAN® TH1 Hauptschutz', tagline: 'Sicherungs- und Temperaturüberwachung', desc: 'Bietet Sicherungs- und Temperaturüberwachung mit potenzialfreien Relaiskontakten in einer Einzelgerätebauweise für flexible Schaltschrankmontage.', pdf: '/pdfs/th1_datasheet_katalog-1.pdf', tag: null },
        { id: 'tytan-rhbus', name: 'TYTAN® RHBus', tagline: 'Modbus RTU bis 28 Geräte', desc: 'Detaillierte Sicherungsüberwachung für bis zu 28 Geräte via Modbus RTU. Erfasst einzelne Temperaturen und Schaltstellungen gleichzeitig.', pdf: '/pdfs/rhbus_datasheet_katalog-update.pdf', tag: 'Smart' },
        { id: 'tytan-thbus', name: 'TYTAN® THBus', tagline: 'Modbus RTU für Temperatur und Position', desc: 'Überwacht bis zu 28 Geräte via Modbus RTU mit individueller Temperatur- und Schaltstellungsüberwachung für smarte Gebäude.', pdf: '/pdfs/thbus_datasheet_katalog-2.pdf', tag: 'Smart' },
        { id: 'rj-fuse', name: 'RJ Sicherungsüberwachung', tagline: '17,8 mm, 1 TE kompakt', desc: 'Einzelgeräte-Sicherungsüberwachung mit nur 17,8 mm / 1 TE Breite, ideal für enge Einbausituationen in Schaltschränken und Verteilungen.', pdf: '/pdfs/rjueberwachung_datasheet_katalog.pdf', tag: null },
      ],
      specs: [
        { key: 'System', value: 'TYTAN® II' },
        { key: 'Nennstrom', value: 'bis 160 A' },
        { key: 'Nennspannung', value: '230 / 400 V AC' },
        { key: 'Schutzart', value: 'IP20' },
        { key: 'Abschließbar', value: 'Ja' },
        { key: 'Plombierbar', value: 'Ja' },
        { key: 'Montage', value: 'Hutschiene EN 60715' },
        { key: 'Zertifizierung', value: 'CE, VDE, EN 60269' },
      ],
      heroLabel: 'TYTAN® II · RH-Serie · RJ-Überwachung',
      heroTitle1: 'Haupt',
      heroTitle2: 'schutz',
      heroDesc: 'Moderner und sicherer Schutz für elektrische Einspeisungen mit vollcodierten Sicherungssteckern, integriertem Blinkmelder, Temperaturüberwachung und Modbus-Anbindung.',
      breadcrumbCurrent: 'Hauptschutz',
      badges: ['ISO 9001', 'ISO 14001', 'CE / VDE', 'Made in Germany'],
      stats: [{ v: '9', l: 'Produktmodelle' }, { v: '160A', l: 'Max. Nennstrom' }, { v: '400V', l: 'Systemspannung' }, { v: '1985', l: 'Gründungsjahr' }],
      rangeTitle: 'TYTAN® II und RH-Serien',
      rangeSub: '9 Hauptschutzmodelle von kompakter Einzelüberwachung bis zur vollständigen Modbus-Netzintegration.',
      explorerBody: 'Betrachten Sie die Hauptschutz-Einheit aus jedem Winkel. Drehen, zoomen und verschieben Sie das Modell, um die Konstruktion im Detail zu prüfen.',
      viewerBadge: 'TYTAN® II Hauptschutz',
      specsSub: 'Wesentliche Parameter des TYTAN® II Hauptschutzsystems. Modellspezifische Werte finden Sie in den jeweiligen Datenblättern.',
      imageAlt: 'Hauptschutz',
      ctaTitle: 'Interesse an Hauptschutz?',
      certLabel: 'ISO 9001 · ISO 14001 zertifiziert',
    },
    relais: {
      models: [
        { id: 'net-monitor', name: 'Netzüberwachungsrelais', tagline: '3-phasig, Neutralleiter, LED', desc: 'All-in-one-Netzrelais für Dreiphasensysteme mit Unterspannungs-, Phasenausfall-, Phasenfolge- und Neutralleiterüberwachung. Integrierte LED-Fehleranzeige.', pdf: '/pdfs/Alle-Relais_datasheet_katalog_update.pdf', tag: 'Flaggschiff' },
        { id: 'undervoltage', name: 'Unterspannungsrelais', tagline: 'Einstellbare Auslöseschwelle', desc: 'Überwacht Phasenspannungen kontinuierlich gegen einen einstellbaren Schwellwert. Schaltet bei Unterspannung das Ausgangsrelais und aktiviert die Fehler-LED.', pdf: '/pdfs/Alle-Relais_datasheet_katalog_update.pdf', tag: null },
        { id: 'phase-failure', name: 'Phasenausfallwächter', tagline: 'Einzelphasenerkennung', desc: 'Erkennt zuverlässig den Ausfall einzelner Phasen in Dreiphasensystemen. Schützt Motoren und Anlagen vor Einphasenbetrieb.', pdf: '/pdfs/Alle-Relais_datasheet_katalog_update.pdf', tag: null },
        { id: 'phase-seq', name: 'Drehfeldrelais', tagline: 'Schutz der Drehrichtung', desc: 'Prüft die korrekte L1-L2-L3-Reihenfolge vor dem Freigeben der Last und verhindert teure Motorschäden durch Phasenvertauschung.', pdf: '/pdfs/Alle-Relais_datasheet_katalog_update.pdf', tag: null },
        { id: 'neutral-mon', name: 'Neutralleiterwächter', tagline: 'Vollständige Netzüberwachung', desc: 'Erweitert die Überwachung auf den Neutralleiter für eine vollständige Vierleiter-Netzüberwachung. Ideal für TN-S-Systeme.', pdf: '/pdfs/Alle-Relais_datasheet_katalog_update.pdf', tag: null },
        { id: 'compact-din', name: 'Kompaktes Hutschienenrelais', tagline: '17,5 mm, Universalbefestigung', desc: 'Schlankes 17,5-mm-Hutschienenrelais für Netzüberwachung bei minimalem Platzbedarf. Universelle 3 x 400 V AC Versorgung, IP20.', pdf: '/pdfs/Alle-Relais_datasheet_katalog_update.pdf', tag: 'Kompakt' },
      ],
      specs: [
        { key: 'Überwachung', value: 'Unterspannung, Phasenausfall, Phasenfolge' },
        { key: 'Nennspannung', value: '3 x 400 V AC' },
        { key: 'Frequenz', value: '50 / 60 Hz' },
        { key: 'Auslöseschwelle', value: 'einstellbar' },
        { key: 'Ausgangsrelais', value: '1 Wechsler' },
        { key: 'Nennstrom Kontakt', value: '8 A / 250 V' },
        { key: 'Schutzart', value: 'IP20' },
        { key: 'Zertifizierung', value: 'CE, VDE' },
      ],
      heroLabel: 'Netzüberwachung · Phasenschutz',
      heroTitle1: 'Überwachungs',
      heroTitle2: 'relais',
      heroDesc: 'Zuverlässige Netzüberwachungsrelais für Dreiphasensysteme mit Unterspannungsschutz, Phasenausfallerkennung und Drehfeldüberwachung in kompakter Hutschienenbauform.',
      breadcrumbCurrent: 'Relais',
      badges: ['ISO 9001', 'ISO 14001', 'CE / VDE', 'Made in Germany'],
      stats: [{ v: '6', l: 'Relais-Typen' }, { v: '400V', l: 'Nennspannung' }, { v: '8A', l: 'Kontaktstrom' }, { v: '1985', l: 'Gründungsjahr' }],
      rangeTitle: 'Netzüberwachungsrelais',
      rangeSub: '6 Relaistypen von All-in-one-Netzüberwachung bis zu spezialisierten Schutzfunktionen.',
      explorerBody: 'Betrachten Sie das Relaismodul aus jedem Winkel. Drehen, zoomen und verschieben Sie das Modell, um Hutschienenformat und Anschlüsse im Detail zu prüfen.',
      viewerBadge: 'Bruchmann Überwachungsrelais',
      specsSub: 'Wesentliche Parameter der Bruchmann Relais-Baureihe. Vollständige Werte finden Sie im Produktkatalog.',
      imageAlt: 'Überwachungsrelais',
      ctaTitle: 'Interesse an der Relais-Baureihe?',
      certLabel: 'ISO 9001 · ISO 14001 zertifiziert',
    },
    sammelschienensystem: {
      models: [
        { id: 'tytan-r', name: 'TYTAN® R', tagline: '27 mm, allpoliges Schalten', desc: 'Blinkmelder, allpoliges Schalten, Sicherungsstecker und abschließbare Bauweise. Optional Strommessung und Signalisierung. Kompatibel mit 5-10 mm Sammelschienen in 12-30 mm Breite.', pdf: '/pdfs/tytan_r_datasheet_katalog.pdf', tag: 'Beliebt' },
        { id: 'coron-r', name: 'CORON® R', tagline: 'Kompakte flache Bauform', desc: 'Kompakte, flache Bauweise mit Blinkmelder, Sicherungsstecker, abschließbarer Konstruktion und optionaler Erweiterung für flexible Systemintegration.', pdf: '/pdfs/coron_r_datasheet_katalog.pdf', tag: null },
        { id: 'tytan-ii-bs', name: 'TYTAN® II auf Geräteadaptern', tagline: '2-polige und 3-polige Varianten', desc: '2-polig 81 mm / 3-polig 108 mm. Montage auf 60-mm-Systemgerätea­d­aptern. Kompatibel mit Kupfersammelschienen von 12 bis 30 mm Breite und 5 oder 10 mm Dicke.', pdf: '/pdfs/tytanII_geraeteadapter_hs_datasheet_katalog-update_2.pdf', tag: 'Flaggschiff' },
        { id: 'tytan-adapter', name: 'TYTAN® Geräteadapter', tagline: 'Für D0-Lasttrennschalter', desc: 'Lasttrennschalterfähig mit TYTAN® D0. Vorbereitet für den 60-mm-Sammelschienenadapter mit integrierter Einspeisung und Berührungsschutz.', pdf: '/pdfs/tytan_geraeteadapter_datasheet_katalog.pdf', tag: null },
        { id: 'device-adapter', name: 'Geräteadapter', tagline: 'Verstellbare Montageschiene', desc: 'Montageschiene millimetergenau verstellbar. Mit verlustarmer Doppelkontaktierung und ansteckbarer Erweiterungsfunktion für maximale Flexibilität.', pdf: '/pdfs/adapter_sammelschiene_geraete_datasheet_bm.pdf', tag: null },
        { id: 'tytan-rh1-bs', name: 'TYTAN® RH1 Hauptschutz', tagline: 'Sicherungs- und Temperaturüberwachung', desc: 'Sicherungs- und Temperaturüberwachung mit potenzialfreien Relaiskontakten für die direkte Einbindung in Gebäude- und Überwachungssysteme.', pdf: '/pdfs/rh1_datasheet_katalog-update.pdf', tag: null },
        { id: 'tytan-rhbus-bs', name: 'TYTAN® RHBus', tagline: 'Modbus RTU bis 28 Geräte', desc: 'Detaillierte Sicherungsüberwachung für bis zu 28 Geräte via Modbus RTU. Erfasst einzelne Temperaturen und Schaltstellungen gleichzeitig.', pdf: '/pdfs/rhbus_datasheet_katalog-update.pdf', tag: 'Smart' },
        { id: 'tytan-rh4-bs', name: 'TYTAN® RH4 Hauptschutz', tagline: 'Selbstversorgt, 36 mm / 2 TE', desc: 'Selbstversorgter Blinkmelder in einem 36 mm / 2 TE breiten, abschließbaren Gehäuse mit Sicherungsstecker, ohne zusätzliche Hilfsspannung.', pdf: '/pdfs/rh4_datasheet_katalog-update.pdf', tag: null },
        { id: 'd0-clip', name: 'D0 Clip-Sicherungssockel', tagline: 'E18 Edelstahlklemme', desc: 'Markantes Beschriftungsfeld, Edelstahlklemme, seitlicher Fingerschutz und rückseitiger Steck-Berührungsschutz für sichere D0-Sockelinstallationen.', pdf: '/pdfs/d0_sicherungssockele18_datasheet_katalog.pdf', tag: null },
        { id: 'pancero', name: 'PANCERO Schutzprofil', tagline: 'Werkzeuggesichert, 1000 mm', desc: 'Schnappverschluss mit Werkzeugöffnung. Hitzebeständiger PA66-Kunststoff, 1000 mm Länge. Für 12 bis 30 mm Breiten, individuell kürzbar.', pdf: null, tag: null },
        { id: 'busbar-support', name: 'Sammelschienen-Träger', tagline: 'Wendbar für 12 bis 30 mm', desc: 'Wendbare Basis für 12 bis 30 mm Sammelschienen in 5 und 10 mm Dicke. Kompatibel mit Striebel-&-John-Verteilern und Innenmontage.', pdf: '/pdfs/sammelschienentraeger_datasheet_katalog-update.pdf', tag: null },
      ],
      specs: [
        { key: 'Systemspannung', value: 'bis 690 V AC' },
        { key: 'Nennstrom', value: 'bis 1000 A' },
        { key: 'Sammelschienenbreiten', value: '12 / 15 / 20 / 25 / 30 mm' },
        { key: 'Sammelschienendicken', value: '5 mm / 10 mm' },
        { key: 'Material', value: 'Kupfer / Aluminium' },
        { key: 'Schutzart', value: 'IP20 - IP40' },
        { key: 'Montage', value: 'Vertikal / Horizontal' },
        { key: 'Zertifizierung', value: 'CE, EN 61439' },
      ],
      heroLabel: 'TYTAN® R · CORON® R · Geräteadapter',
      heroTitle1: 'Sammelschienen',
      heroTitle2: 'system',
      heroDesc: 'Kompakte und flexibel anpassbare Sammelschienensysteme für effiziente Energieverteilung mit hoher Stromtragfähigkeit, modularem Aufbau und bewährtem Schutz.',
      breadcrumbCurrent: 'Sammelschienensystem',
      badges: ['ISO 9001', 'ISO 14001', 'CE / VDE', 'Made in Germany'],
      stats: [{ v: '11', l: 'Produktmodelle' }, { v: '1000A', l: 'Max. Nennstrom' }, { v: '690V', l: 'Max. Nennspannung' }, { v: '1985', l: 'Gründungsjahr' }],
      rangeTitle: 'TYTAN® R · CORON® R · Adapter',
      rangeSub: '11 modulare Komponenten vom kompakten Sicherungssockel bis zu vollständigen Überwachungs- und Schutzlösungen.',
      explorerBody: 'Betrachten Sie das Sammelschienensystem aus jedem Winkel. Drehen, zoomen und verschieben Sie das Modell, um die modulare Konstruktion zu prüfen.',
      viewerBadge: 'TYTAN® Sammelschienensystem',
      specsSub: 'Wesentliche Parameter der Bruchmann Sammelschienensysteme. Komponentenspezifische Werte finden Sie in den jeweiligen Datenblättern.',
      imageAlt: 'Sammelschienensystem',
      ctaTitle: 'Interesse am Sammelschienensystem?',
      certLabel: 'ISO 9001 · ISO 14001 zertifiziert',
    },
    zaehlersteckklemmen: {
      models: [
        { id: 'adock-3phase', name: 'ADOCK® 3-Phasen Standard', tagline: 'DIN 43857 · 3-Punkt-Montage', desc: 'Dreiphasige Zählersteckklemme für kWh-Zähler nach DIN 43857 mit 3-Punkt-Befestigung. Patentiertes ADOCK®-Kontaktsystem für sicheren, werkzeuglosen Zählerwechsel.', pdf: '/pdfs/adock_datasheet_katalog-update-1.pdf', tag: 'Flaggschiff' },
        { id: 'adock-vfree', name: 'ADOCK® Spannungsfreier Tausch', tagline: 'Kein Spannungsausfall erforderlich', desc: 'Wechsel von kWh-Zählern ohne Unterbrechung der Betriebsspannung nachgeschalteter Systeme. Das ADOCK®-Trennprinzip hält die Anlage währenddessen aktiv.', pdf: '/pdfs/adock_datasheet_katalog-update-1.pdf', tag: null },
        { id: 'adock-bottom', name: 'ADOCK® Unterer Anschluss', tagline: 'Kabelführung nach unten', desc: 'Variante mit nach unten geführten Kabelanschlüssen. Ideal für Unterputzverteiler mit eingeschränkter oberer Kabelführung.', pdf: '/pdfs/adock_datasheet_katalog-update-1.pdf', tag: null },
        { id: 'adock-rear', name: 'ADOCK® Rückseitiger Anschluss', tagline: 'Kabelführung nach hinten', desc: 'Rückseitige Anschlussvariante für Installationen mit Kabeleinführung hinter dem Feld. Kompatibel mit Standardzählern nach DIN 43857.', pdf: '/pdfs/adock_datasheet_katalog-update-1.pdf', tag: null },
        { id: 'adock-compact', name: 'ADOCK® Kompakt', tagline: 'Minimaler Platzbedarf · IP20', desc: 'Schlanke ADOCK®-Ausführung für enge Einbausituationen. Geringer Platzbedarf bei voller DIN-43857-Konformität und 100-A-Belastbarkeit.', pdf: '/pdfs/adock_datasheet_katalog-update-1.pdf', tag: 'Kompakt' },
        { id: 'adock-cover', name: 'ADOCK® mit Abdeckung', tagline: 'Integrierte Abdeckung · manipulationssicher', desc: 'Mit integrierter Klemmenraumabdeckung. Kompatibel mit Standard-Zählerabdeckungen und ideal für zusätzlichen Schutz im Versorgerumfeld.', pdf: '/pdfs/adock_datasheet_katalog-update-1.pdf', tag: null },
      ],
      specs: [
        { key: 'System', value: 'ADOCK®' },
        { key: 'Kompatibilität', value: 'DIN 43857, 3-Punkt-Befestigung' },
        { key: 'Nennstrom', value: 'bis 100 A' },
        { key: 'Nennspannung', value: '230 / 400 V AC' },
        { key: 'Anschluss', value: 'unten oder hinten' },
        { key: 'Schutzart', value: 'IP20' },
        { key: 'Montage', value: 'Hutschiene EN 60715' },
        { key: 'Zertifizierung', value: 'CE, VDE, MID' },
      ],
      heroLabel: 'ADOCK® System · DIN 43857',
      heroTitle1: 'Zählersteck',
      heroTitle2: 'klemmen',
      heroDesc: 'Zählersteckklemmen für kWh-Zähler. Das patentierte ADOCK®-System ermöglicht den spannungsfreien Zählerwechsel ohne Unterbrechung nachgeschalteter Verbraucher.',
      breadcrumbCurrent: 'Zählersteckklemmen',
      badges: ['ISO 9001', 'ISO 14001', 'CE / VDE / MID', 'Made in Germany'],
      stats: [{ v: '6', l: 'Produktvarianten' }, { v: '100A', l: 'Max. Nennstrom' }, { v: '400V', l: 'Max. Nennspannung' }, { v: '1985', l: 'Gründungsjahr' }],
      rangeTitle: 'ADOCK® Zählersteckklemmen',
      rangeSub: '6 ADOCK®-Varianten von Standard-3-Phasen-Klemmen bis zu kompakten und rückseitigen Anschlusslösungen.',
      explorerBody: 'Betrachten Sie die ADOCK®-Zählersteckklemme aus jedem Winkel. Drehen, zoomen und verschieben Sie das Modell, um Kontaktsystem und Anschlüsse im Detail zu prüfen.',
      viewerBadge: 'ADOCK® Zählersteckklemme',
      specsSub: 'Wesentliche Parameter der ADOCK®-Baureihe. Vollständige Werte finden Sie im Produktkatalog.',
      imageAlt: 'ADOCK® Zählersteckklemme',
      ctaTitle: 'Interesse am ADOCK® System?',
      certLabel: 'ISO 9001 · CE · VDE · MID zertifiziert',
    },
  },
  en: {},
}

productDetailContent.en = {
  sicherungsschaltgeraete: {
    ...productDetailContent.de.sicherungsschaltgeraete,
    models: [
      { id: 'tytan-i', name: 'TYTAN® I', tagline: 'Universal fuse plug', desc: 'Universal fuse plug with integrated blink indicator. Compatible with circuit breakers. Sealable.', pdf: '/pdfs/tytan_I_datasheet_katalog.pdf', tag: 'Popular' },
      { id: 'tytan-ii', name: 'TYTAN® II', tagline: 'Full-coded protection', desc: 'Full coding for 1 to 63 A with continuous intermediate ratings. Blink indicator integrated directly in the plug.', pdf: '/pdfs/tytan_II_datasheet_katalog-neu2.pdf', tag: 'Flagship' },
      { id: 'tytan-t', name: 'TYTAN® T', tagline: '4 HP compact unit', desc: '4 HP width design with optional monitoring features. Load break switch for multiple fuse types.', pdf: '/pdfs/tytan_T_datasheet_katalog-neu.pdf', tag: null },
      { id: 'tytan-t4p', name: 'TYTAN® T4P', tagline: 'Multi-fuse load switch', desc: 'Load break switch supporting D0 1 / D0 2 / D0 3 fuse types in one compact 4 HP unit.', pdf: '/pdfs/tytan_T4p_datasheet_katalog.pdf', tag: null },
      { id: 'tytan-t4h', name: 'TYTAN® T4H/T4HP/T4HR', tagline: 'Phase monitoring', desc: 'Compact 4 HP width with integrated phase sequence and phase failure monitoring.', pdf: '/pdfs/t4h_p_r_datasheet_katalog.pdf', tag: null },
      { id: 'tytan-th1', name: 'TYTAN® TH1', tagline: 'Fuse plus temperature', desc: 'Combines fuse protection with integrated temperature monitoring for early overload detection.', pdf: '/pdfs/th1_datasheet_katalog.pdf', tag: null },
      { id: 'tytan-thbus', name: 'TYTAN® THBus', tagline: 'Modbus RTU interface', desc: 'Monitors up to 28 devices simultaneously via Modbus RTU, ideal for smart building integration.', pdf: '/pdfs/thbus_datasheet_katalog.pdf', tag: 'Smart' },
      { id: 'coron-duo', name: 'CORON® DUO', tagline: '27 mm per pole', desc: '27 mm per-pole width with optional integrated auxiliary switch. Modular and space-efficient design.', pdf: '/pdfs/coron_duo_datasheet_katalog-neu.pdf', tag: null },
      { id: 'coron-2', name: 'CORON® 2', tagline: 'Seal and lock', desc: 'Sealable and lockable with padlock compatibility for maximum protection against unauthorised access.', pdf: '/pdfs/coron_2_datasheet_katalog.pdf', tag: null },
      { id: 'in-on', name: 'IN-ON', tagline: 'Push-button trip', desc: 'Sealable and lockable with push-button trip release. Simple and safe operation for industrial use.', pdf: '/pdfs/in-on_datasheet_katalog-update.pdf', tag: null },
    ],
    specs: [
      { key: 'Product series', value: 'TYTAN®, CORON®, IN-ON' },
      { key: 'Rated current', value: 'up to 100 A' },
      { key: 'Rated voltage', value: 'up to 690 V AC' },
      { key: 'Fuse types', value: 'D0 1, D0 2, D0 3' },
      { key: 'Protection class', value: 'IP20' },
      { key: 'Mounting', value: 'DIN rail EN 60715' },
      { key: 'Temperature range', value: '-25 °C to +55 °C' },
      { key: 'Certification', value: 'CE, VDE, EN 60269' },
    ],
    heroTitle1: 'Fuse-Combination',
    heroTitle2: 'Units',
    heroDesc: 'Professional fuse switch disconnectors for DIN rails with blink indicator, measuring plug and temperature monitoring. Klaus Bruchmann GmbH, since 1985.',
    breadcrumbCurrent: 'Fuse-Combination Units',
    stats: [{ v: '10+', l: 'Product Models' }, { v: '100A', l: 'Max Rated Current' }, { v: '690V', l: 'Max Rated Voltage' }, { v: '1985', l: 'Year Founded' }],
    rangeSub: '10 specialist models from basic protection to smart Modbus-connected monitoring.',
    explorerBody: 'Inspect the fuse-combination unit from every angle. Drag, zoom and pan to examine the construction in detail.',
    specsSub: 'Parameters across the TYTAN® and CORON® families. Refer to individual datasheets for model-specific values.',
    imageAlt: 'Fuse-combination unit',
    ctaTitle: 'Interested in Fuse-Combination Units?',
    certLabel: 'ISO 9001 · ISO 14001 Certified',
  },
  hauptschutz: {
    ...productDetailContent.de.hauptschutz,
    models: [
      { id: 'tytan-ii-hs', name: 'TYTAN® II', tagline: 'Full-coded main protection', desc: 'Blink indicator in the plug, full coding for all current ratings. Sealable and lockable design for maximum security.', pdf: '/pdfs/tytanII_hs_datasheet_katalog-neu-1.pdf', tag: 'Flagship' },
      { id: 'tytan-ii-adapter', name: 'TYTAN® II Device Adapters', tagline: '2-pole and 3-pole', desc: '2-pole 81 mm / 3-pole 108 mm. Mounted on 60 mm system adapters for copper conductors 12 to 30 mm wide.', pdf: '/pdfs/tytanII_geraeteadapter_hs_datasheet_katalog-update_2.pdf', tag: null },
      { id: 'tytan-t4h-hs', name: 'TYTAN® T4H / T4HP / T4HR', tagline: 'Multi-phase monitoring', desc: 'Compact 4 HP width. Potential-free changeover contact for fuse monitoring of L1, L2 and L3. Includes blink indicator and universal fuse plug.', pdf: '/pdfs/t4h_p_r_datasheet_katalog-1.pdf', tag: null },
      { id: 'tytan-rh4', name: 'TYTAN® RH4', tagline: 'Self-powered indicator', desc: 'Blink indicator in a self-powered design. 36 mm / 2 HP wide lockable housing with fuse plug and no auxiliary power required.', pdf: '/pdfs/rh4_datasheet_katalog-update.pdf', tag: null },
      { id: 'tytan-rh1', name: 'TYTAN® RH1 Main Protection', tagline: 'Fuse and temperature monitoring', desc: 'Combines fuse and temperature monitoring with potential-free relay contacts for direct integration into building management systems.', pdf: '/pdfs/rh1_datasheet_katalog-update.pdf', tag: null },
      { id: 'tytan-th1', name: 'TYTAN® TH1 Main Protection', tagline: 'Fuse and temperature monitoring', desc: 'Provides fuse and temperature monitoring with potential-free relay contacts in a single-unit design for flexible panel installation.', pdf: '/pdfs/th1_datasheet_katalog-1.pdf', tag: null },
      { id: 'tytan-rhbus', name: 'TYTAN® RHBus', tagline: 'Modbus RTU for up to 28 devices', desc: 'Detailed fuse monitoring for up to 28 devices via Modbus RTU, tracking individual temperatures and switching positions simultaneously.', pdf: '/pdfs/rhbus_datasheet_katalog-update.pdf', tag: 'Smart' },
      { id: 'tytan-thbus', name: 'TYTAN® THBus', tagline: 'Modbus RTU for temperature and position', desc: 'Monitors up to 28 devices via Modbus RTU with individual temperature and switching-position tracking for smart buildings.', pdf: '/pdfs/thbus_datasheet_katalog-2.pdf', tag: 'Smart' },
      { id: 'rj-fuse', name: 'RJ Fuse Monitoring', tagline: '17.8 mm, 1 HP compact', desc: 'Single-unit fuse monitoring at only 17.8 mm / 1 HP width, ideal for tight panel and switchgear installations.', pdf: '/pdfs/rjueberwachung_datasheet_katalog.pdf', tag: null },
    ],
    specs: [
      { key: 'System', value: 'TYTAN® II' },
      { key: 'Rated current', value: 'up to 160 A' },
      { key: 'Rated voltage', value: '230 / 400 V AC' },
      { key: 'Protection class', value: 'IP20' },
      { key: 'Lockable', value: 'Yes' },
      { key: 'Sealable', value: 'Yes' },
      { key: 'Mounting', value: 'DIN rail EN 60715' },
      { key: 'Certification', value: 'CE, VDE, EN 60269' },
    ],
    heroTitle1: 'Main',
    heroTitle2: 'Protection',
    heroDesc: 'Modern and safe protection for electrical mains with fully coded fuse plugs, integrated blink indicator, temperature monitoring and Modbus connectivity.',
    stats: [{ v: '9', l: 'Product Models' }, { v: '160A', l: 'Max Rated Current' }, { v: '400V', l: 'System Voltage' }, { v: '1985', l: 'Year Founded' }],
    rangeSub: '9 main protection models from compact single-unit monitoring to full Modbus network integration.',
    explorerBody: 'Inspect the main protection unit from every angle. Drag, zoom and pan to examine the construction in detail.',
    specsSub: 'Key parameters of the TYTAN® II main protection system. Refer to individual datasheets for model-specific values.',
    ctaTitle: 'Interested in Main Protection?',
    certLabel: 'ISO 9001 · ISO 14001 Certified',
  },
  relais: {
    ...productDetailContent.de.relais,
    models: [
      { id: 'net-monitor', name: 'Network Monitoring Relay', tagline: '3-phase, neutral, LED', desc: 'All-in-one network relay for three-phase systems with undervoltage, phase failure, phase sequence and neutral conductor monitoring. Integrated LED fault indicator.', pdf: '/pdfs/Alle-Relais_datasheet_katalog_update.pdf', tag: 'Flagship' },
      { id: 'undervoltage', name: 'Undervoltage Relay', tagline: 'Adjustable trip threshold', desc: 'Continuously monitors phase voltages against an adjustable threshold. Trips the output relay and activates the fault LED on undervoltage.', pdf: '/pdfs/Alle-Relais_datasheet_katalog_update.pdf', tag: null },
      { id: 'phase-failure', name: 'Phase Failure Monitor', tagline: 'Individual phase detection', desc: 'Reliably detects the loss of any individual phase in three-phase systems and protects motors and equipment from single-phasing.', pdf: '/pdfs/Alle-Relais_datasheet_katalog_update.pdf', tag: null },
      { id: 'phase-seq', name: 'Phase Sequence Relay', tagline: 'Rotation direction guard', desc: 'Verifies the correct L1-L2-L3 order before enabling the load and prevents motor damage caused by phase reversal.', pdf: '/pdfs/Alle-Relais_datasheet_katalog_update.pdf', tag: null },
      { id: 'neutral-mon', name: 'Neutral Conductor Monitor', tagline: 'Full network supervision', desc: 'Extends monitoring to the neutral conductor for complete four-wire supervision, ideal for TN-S systems.', pdf: '/pdfs/Alle-Relais_datasheet_katalog_update.pdf', tag: null },
      { id: 'compact-din', name: 'Compact DIN Rail Relay', tagline: '17.5 mm, universal mounting', desc: 'Slim 17.5 mm DIN rail relay for network monitoring in minimal panel space. Universal 3 x 400 V AC supply, IP20.', pdf: '/pdfs/Alle-Relais_datasheet_katalog_update.pdf', tag: 'Compact' },
    ],
    specs: [
      { key: 'Monitoring', value: 'Undervoltage, phase failure, phase sequence' },
      { key: 'Rated voltage', value: '3 x 400 V AC' },
      { key: 'Frequency', value: '50 / 60 Hz' },
      { key: 'Trip threshold', value: 'adjustable' },
      { key: 'Output relay', value: '1 changeover contact' },
      { key: 'Contact rated current', value: '8 A / 250 V' },
      { key: 'Protection class', value: 'IP20' },
      { key: 'Certification', value: 'CE, VDE' },
    ],
    heroTitle1: 'Monitoring',
    heroTitle2: 'Relays',
    heroDesc: 'Reliable network monitoring relays for three-phase systems with undervoltage protection, phase-failure detection and phase-sequence supervision in a compact DIN rail package.',
    stats: [{ v: '6', l: 'Relay Types' }, { v: '400V', l: 'Rated Voltage' }, { v: '8A', l: 'Contact Current' }, { v: '1985', l: 'Year Founded' }],
    rangeSub: '6 relay types from all-in-one network supervision to dedicated protective functions.',
    explorerBody: 'Inspect the relay module from every angle. Drag, zoom and pan to examine the DIN rail form factor and terminals in detail.',
    specsSub: 'Key parameters of the Bruchmann relay range. Refer to the product catalog for complete specifications.',
    ctaTitle: 'Interested in the Relay Range?',
    certLabel: 'ISO 9001 · ISO 14001 Certified',
  },
  sammelschienensystem: {
    ...productDetailContent.de.sammelschienensystem,
    models: [
      { id: 'tytan-r', name: 'TYTAN® R', tagline: '27 mm, all-pole switching', desc: 'Blink indicator, all-pole switching, fuse plug and lockable design. Optional current measurement and signalling. Compatible with 5 to 10 mm busbars, 12 to 30 mm wide.', pdf: '/pdfs/tytan_r_datasheet_katalog.pdf', tag: 'Popular' },
      { id: 'coron-r', name: 'CORON® R', tagline: 'Compact low-profile design', desc: 'Compact low-profile design with blink indicator, fuse plug, lockable construction and optional extension for flexible system integration.', pdf: '/pdfs/coron_r_datasheet_katalog.pdf', tag: null },
      { id: 'tytan-ii-bs', name: 'TYTAN® II on Device Adapters', tagline: '2-pole and 3-pole variants', desc: '2-pole 81 mm / 3-pole 108 mm. Mounted on 60 mm system device adapters. Compatible with copper busbars 12 to 30 mm wide and 5 or 10 mm thick.', pdf: '/pdfs/tytanII_geraeteadapter_hs_datasheet_katalog-update_2.pdf', tag: 'Flagship' },
      { id: 'tytan-adapter', name: 'TYTAN® Device Adapter', tagline: 'Ready for D0 load break switch', desc: 'Load break switch capability with TYTAN® D0. Ready for 60 mm busbar adapter connection with integrated feed-in and touch protection.', pdf: '/pdfs/tytan_geraeteadapter_datasheet_katalog.pdf', tag: null },
      { id: 'device-adapter', name: 'Device Adapter', tagline: 'Adjustable mounting rail', desc: 'Mounting rail adjustable in millimetre increments. Features low-loss double contacting and attachable extension functionality for maximum flexibility.', pdf: '/pdfs/adapter_sammelschiene_geraete_datasheet_bm.pdf', tag: null },
      { id: 'tytan-rh1-bs', name: 'TYTAN® RH1 Main Protection', tagline: 'Fuse and temperature monitoring', desc: 'Fuse monitoring and temperature supervision with potential-free relay contacts for direct integration into building and monitoring systems.', pdf: '/pdfs/rh1_datasheet_katalog-update.pdf', tag: null },
      { id: 'tytan-rhbus-bs', name: 'TYTAN® RHBus', tagline: 'Modbus RTU for up to 28 devices', desc: 'Detailed fuse monitoring for up to 28 devices via Modbus RTU, tracking individual temperatures and switching positions simultaneously.', pdf: '/pdfs/rhbus_datasheet_katalog-update.pdf', tag: 'Smart' },
      { id: 'tytan-rh4-bs', name: 'TYTAN® RH4 Main Protection', tagline: 'Self-powered, 36 mm / 2 HP', desc: 'Self-powered blink indicator in a 36 mm / 2 HP lockable housing with fuse plug and no additional auxiliary power.', pdf: '/pdfs/rh4_datasheet_katalog-update.pdf', tag: null },
      { id: 'd0-clip', name: 'D0 Clip Fuse Base', tagline: 'E18 stainless-steel clamp', desc: 'Distinctive labelling field, stainless-steel clamp, lateral finger protection and rear plug-in touch guard for safe D0 fuse base installations.', pdf: '/pdfs/d0_sicherungssockele18_datasheet_katalog.pdf', tag: null },
      { id: 'pancero', name: 'PANCERO Protection Profile', tagline: 'Tool-secured, 1000 mm', desc: 'Snap-lock closure requiring tool access. Heat-resistant PA66 plastic, 1000 mm length. Compatible with widths from 12 to 30 mm and cuttable to size.', pdf: null, tag: null },
      { id: 'busbar-support', name: 'Busbar Support', tagline: 'Reversible for 12 to 30 mm', desc: 'Reversible base for 12 to 30 mm busbars in 5 and 10 mm thickness. Compatible with Striebel & John distribution boards and internal mounting.', pdf: '/pdfs/sammelschienentraeger_datasheet_katalog-update.pdf', tag: null },
    ],
    specs: [
      { key: 'System voltage', value: 'up to 690 V AC' },
      { key: 'Rated current', value: 'up to 1000 A' },
      { key: 'Busbar widths', value: '12 / 15 / 20 / 25 / 30 mm' },
      { key: 'Busbar thicknesses', value: '5 mm / 10 mm' },
      { key: 'Material', value: 'Copper / Aluminium' },
      { key: 'Protection class', value: 'IP20 - IP40' },
      { key: 'Mounting', value: 'Vertical / Horizontal' },
      { key: 'Certification', value: 'CE, EN 61439' },
    ],
    heroTitle1: 'Busbar',
    heroTitle2: 'System',
    heroDesc: 'Compact and flexibly adaptable busbar systems for efficient power distribution with high current capacity, modular design and proven protection.',
    stats: [{ v: '11', l: 'Product Models' }, { v: '1000A', l: 'Max Rated Current' }, { v: '690V', l: 'Max Rated Voltage' }, { v: '1985', l: 'Year Founded' }],
    rangeSub: '11 modular components from compact fuse bases to complete monitoring and protection solutions.',
    explorerBody: 'Inspect the busbar system from every angle. Drag, zoom and pan to examine the modular construction.',
    specsSub: 'Key parameters of the Bruchmann busbar system range. Refer to individual datasheets for component-specific values.',
    ctaTitle: 'Interested in the Busbar System?',
    certLabel: 'ISO 9001 · ISO 14001 Certified',
  },
  zaehlersteckklemmen: {
    ...productDetailContent.de.zaehlersteckklemmen,
    models: [
      { id: 'adock-3phase', name: 'ADOCK® 3-Phase Standard', tagline: 'DIN 43857, 3-point mounting', desc: 'Three-phase meter terminal block for kWh meters to DIN 43857 with 3-point mounting. Patented ADOCK® contact system for safe tool-free meter exchange.', pdf: '/pdfs/adock_datasheet_katalog-update-1.pdf', tag: 'Flagship' },
      { id: 'adock-vfree', name: 'ADOCK® Voltage-Free Exchange', tagline: 'No power interruption required', desc: 'Exchange kWh meters without interrupting the operating voltage of downstream systems. The ADOCK® isolation principle keeps the installation live during the swap.', pdf: '/pdfs/adock_datasheet_katalog-update-1.pdf', tag: null },
      { id: 'adock-bottom', name: 'ADOCK® Bottom Connection', tagline: 'Downward cable routing', desc: 'Variant with all cable connections routed downward. Ideal for flush-mounted boards with restricted top cable routing.', pdf: '/pdfs/adock_datasheet_katalog-update-1.pdf', tag: null },
      { id: 'adock-rear', name: 'ADOCK® Rear Connection', tagline: 'Rear cable routing', desc: 'Rear connection variant for installations requiring cable entry from behind the panel. Compatible with standard meters to DIN 43857.', pdf: '/pdfs/adock_datasheet_katalog-update-1.pdf', tag: null },
      { id: 'adock-compact', name: 'ADOCK® Compact', tagline: 'Minimal footprint · IP20', desc: 'Slim-profile ADOCK® design for confined installation situations. Minimal space requirement with full DIN 43857 compliance and 100 A rating.', pdf: '/pdfs/adock_datasheet_katalog-update-1.pdf', tag: 'Compact' },
      { id: 'adock-cover', name: 'ADOCK® with Cover', tagline: 'Integrated cover · tamper-safe', desc: 'Supplied with an integrated terminal-compartment cover. Compatible with standard meter covers for additional protection in utility applications.', pdf: '/pdfs/adock_datasheet_katalog-update-1.pdf', tag: null },
    ],
    specs: [
      { key: 'System', value: 'ADOCK®' },
      { key: 'Compatibility', value: 'DIN 43857, 3-point mounting' },
      { key: 'Rated current', value: 'up to 100 A' },
      { key: 'Rated voltage', value: '230 / 400 V AC' },
      { key: 'Connection', value: 'bottom or rear' },
      { key: 'Protection class', value: 'IP20' },
      { key: 'Mounting', value: 'DIN rail EN 60715' },
      { key: 'Certification', value: 'CE, VDE, MID' },
    ],
    heroTitle1: 'Meter Terminal',
    heroTitle2: 'Blocks',
    heroDesc: 'Plug-in meter terminal blocks for kWh meters. The patented ADOCK® system enables voltage-free meter exchange without interrupting downstream loads.',
    stats: [{ v: '6', l: 'Product Variants' }, { v: '100A', l: 'Max Rated Current' }, { v: '400V', l: 'Max Rated Voltage' }, { v: '1985', l: 'Year Founded' }],
    rangeSub: '6 ADOCK® variants from standard 3-phase terminals to compact and rear-connection layouts.',
    explorerBody: 'Inspect the ADOCK® meter terminal block from every angle. Drag, zoom and pan to examine the contact system and terminals in detail.',
    specsSub: 'Key parameters of the ADOCK® range. Refer to the product catalogue for complete specifications.',
    ctaTitle: 'Interested in the ADOCK® System?',
    certLabel: 'ISO 9001 · CE · VDE · MID Certified',
  },
}

export const careerPageContent = {
  de: {
    stats: [{ v: '40+', l: 'Jahre Exzellenz', n: 40, suffix: '+' }, { v: '25M+', l: 'Produkte gefertigt', n: 25, suffix: 'M+' }, { v: '100%', l: 'Made in Germany', n: 100, suffix: '%' }],
    teamAlt: 'Bruchmann Team',
    teamBadge: 'Bruchmann GmbH Team',
    storyLabel: 'Mitarbeiter-Story',
    storyQuote: 'Echte Stimmen aus unserem Team. Erleben Sie, wie sich Wachstum bei Bruchmann anfühlt.',
    unsolicited: 'Initiativbewerbung',
  },
  en: {
    stats: [{ v: '40+', l: 'Years of excellence', n: 40, suffix: '+' }, { v: '25M+', l: 'Products manufactured', n: 25, suffix: 'M+' }, { v: '100%', l: 'Made in Germany', n: 100, suffix: '%' }],
    teamAlt: 'Bruchmann Team',
    teamBadge: 'Bruchmann GmbH Team',
    storyLabel: 'Employee Story',
    storyQuote: "Real voices from our team. Hear what it's like to grow with Bruchmann.",
    unsolicited: 'Unsolicited Application',
  },
}

export const applicationPageContent = {
  de: {
    pageLabel: 'Bewerbung',
    breadcrumbCareers: 'Karriere',
    breadcrumbApply: 'Bewerben',
    heroTitle: 'Bewerben Sie sich als',
    heroDesc: 'Füllen Sie das Formular aus und laden Sie Ihre Unterlagen hoch. Unser HR-Team unter info@bruchmann-gmbh.de prüft Ihre Bewerbung und meldet sich zeitnah bei Ihnen.',
    requirementsLabel: 'Anforderungen',
    requirementsTitle: 'Was wir suchen',
    niceLabel: 'Wünschenswert',
    niceTitle: 'Zusätzliche Qualifikationen',
    asidePosition: 'Position',
    asideLocation: 'Standort',
    asideContact: 'HR-Kontakt',
    asideHours: 'Bürozeiten',
    officeHours: 'Mo–Do: 08:00–16:00\nFr: 08:00–14:00 Uhr',
    successTitle: 'Bewerbung erhalten!',
    successBody: 'Vielen Dank für Ihre Bewerbung auf die Position {position}. Unser HR-Team prüft Ihre Unterlagen und meldet sich in wenigen Werktagen.',
    backToCareers: 'Zurück zur Karriere',
    goHome: 'Zur Startseite',
    formTitle: 'Ihre Bewerbung',
    requiredHint: 'Felder mit * sind Pflichtfelder.',
    applyingFor: 'Bewerbung für',
    personalInfo: 'Persönliche Angaben',
    firstName: 'Vorname',
    firstNamePlaceholder: 'Vorname',
    lastName: 'Nachname',
    lastNamePlaceholder: 'Nachname',
    gender: 'Geschlecht',
    contactDetails: 'Kontaktdaten',
    email: 'E-Mail-Adresse',
    emailPlaceholder: 'ihre@email.de',
    mobile: 'Mobilnummer',
    mobilePlaceholder: '+49 ...',
    address: 'Adresse',
    street: 'Straße',
    streetPlaceholder: 'Straßenname',
    houseNo: 'Hausnummer',
    postalCode: 'Postleitzahl',
    city: 'Ort',
    cityPlaceholder: 'Ort',
    country: 'Land',
    application: 'Bewerbung',
    message: 'Anschreiben / Nachricht',
    messagePlaceholder: 'Erzählen Sie uns kurz etwas über sich und warum Sie Teil des Bruchmann-Teams werden möchten …',
    documents: 'Unterlagen (Lebenslauf, Zeugnisse)',
    removeFile: 'Datei entfernen',
    uploadCta: 'Zum Hochladen klicken',
    uploadOr: 'oder per Drag & Drop',
    uploadHint: 'PDF, DOC, DOCX — max. 10 MB',
    submit: 'Bewerbung absenden',
    genderOptions: ['Bitte auswählen', 'Männlich', 'Weiblich', 'Nicht-binär', 'Keine Angabe'],
    countries: ['Deutschland', 'Österreich', 'Schweiz', 'Frankreich', 'Niederlande', 'Belgien', 'Italien', 'Spanien', 'Polen', 'Tschechien', 'Vereinigtes Königreich', 'Andere'],
    defaultPosition: 'Initiativbewerbung',
    requirements: {
      electric: {
        must: ['Abgeschlossene Ausbildung in Elektrotechnik oder Mechatronik', 'Erfahrung mit elektronischen Baugruppen und Schaltungsprüfung', 'Kenntnisse relevanter Sicherheits- und Qualitätsstandards', 'Technische Zeichnungen und Schaltpläne lesen können'],
        nice: ['Erfahrung mit Hutschienen-Schutzsystemen', 'Vertrautheit mit ISO-9001-Dokumentation', 'Kenntnisse in SPS oder Automatisierung', 'Englischkenntnisse'],
      },
      sales: {
        must: ['Technischer Hintergrund in Elektrotechnik oder einem verwandten Bereich', 'Erfahrung im industriellen B2B-Vertrieb oder in der Kundenberatung', 'Starke Kommunikations- und Präsentationsfähigkeiten', 'Führerschein Klasse B'],
        nice: ['Bestehendes Netzwerk im Bereich Elektroverteilung', 'Erfahrung mit CRM-Systemen', 'Englischkenntnisse', 'Homeoffice-Ausstattung für hybrides Arbeiten'],
      },
      default: {
        must: ['Relevante Berufsausbildung oder Hochschulabschluss', 'Praktische Erfahrung in einer vergleichbaren Rolle', 'Teamorientierte Haltung mit zuverlässiger Arbeitsweise', 'Deutschkenntnisse auf B2-Niveau oder höher'],
        nice: ['Erfahrung in der Elektrotechnikbranche', 'Kenntnisse von Qualitätsmanagementsystemen', 'Weitere Sprachkenntnisse (Englisch, Französisch)', 'Bereitschaft zu gelegentlichen Dienstreisen'],
      },
    },
  },
  en: {
    pageLabel: 'Job Application',
    breadcrumbCareers: 'Careers',
    breadcrumbApply: 'Apply',
    heroTitle: 'Apply for',
    heroDesc: 'Fill in the form below and upload your documents. Our HR team at info@bruchmann-gmbh.de will review your application and get back to you shortly.',
    requirementsLabel: 'Requirements',
    requirementsTitle: 'What we look for',
    niceLabel: 'Nice to have',
    niceTitle: 'Bonus qualifications',
    asidePosition: 'Position',
    asideLocation: 'Location',
    asideContact: 'Contact HR',
    asideHours: 'Office Hours',
    officeHours: 'Mon–Thu: 08:00–16:00\nFri: 08:00–14:00',
    successTitle: 'Application Received!',
    successBody: 'Thank you for applying for {position}. Our HR team will review your documents and get back to you within a few business days.',
    backToCareers: 'Back to Careers',
    goHome: 'Go to Home',
    formTitle: 'Your Application',
    requiredHint: 'Fields marked with * are required.',
    applyingFor: 'Applying for',
    personalInfo: 'Personal Information',
    firstName: 'First Name',
    firstNamePlaceholder: 'First name',
    lastName: 'Last Name',
    lastNamePlaceholder: 'Last name',
    gender: 'Gender',
    contactDetails: 'Contact Details',
    email: 'Email Address',
    emailPlaceholder: 'your@email.com',
    mobile: 'Mobile Number',
    mobilePlaceholder: '+49 ...',
    address: 'Address',
    street: 'Street Name',
    streetPlaceholder: 'Street name',
    houseNo: 'House No.',
    postalCode: 'Postal Code',
    city: 'City',
    cityPlaceholder: 'City',
    country: 'Country',
    application: 'Application',
    message: 'Cover Letter / Message',
    messagePlaceholder: "Tell us briefly about yourself and why you'd like to join the Bruchmann team…",
    documents: 'Documents (CV, certificates)',
    removeFile: 'Remove file',
    uploadCta: 'Click to upload',
    uploadOr: 'or drag & drop',
    uploadHint: 'PDF, DOC, DOCX — max 10 MB',
    submit: 'Submit Application',
    genderOptions: ['Please select', 'Male', 'Female', 'Non-binary', 'Prefer not to say'],
    countries: ['Germany', 'Austria', 'Switzerland', 'France', 'Netherlands', 'Belgium', 'Italy', 'Spain', 'Poland', 'Czech Republic', 'United Kingdom', 'Other'],
    defaultPosition: 'Unsolicited Application',
    requirements: {
      electric: {
        must: ['Completed apprenticeship in electrical engineering or mechatronics', 'Experience with electronic assemblies and circuit testing', 'Knowledge of relevant safety and quality standards', 'Ability to read technical drawings and schematics'],
        nice: ['Experience with DIN rail protection systems', 'Familiarity with ISO 9001 documentation', 'PLC or automation knowledge', 'English language skills'],
      },
      sales: {
        must: ['Technical background in electrical engineering or a related field', 'Experience in B2B industrial sales or customer consulting', 'Strong communication and presentation skills', 'Driving licence (Class B)'],
        nice: ['Existing network in the electrical distribution sector', 'CRM system experience', 'English language skills', 'Home-office setup for hybrid work'],
      },
      default: {
        must: ['Relevant vocational training or university degree', 'Hands-on experience in a comparable role', 'Team-oriented mindset with reliable work ethic', 'German language skills (B2 or higher)'],
        nice: ['Experience in the electrical engineering industry', 'Knowledge of quality management systems', 'Additional language skills (English, French)', 'Willingness for occasional travel'],
      },
    },
  },
}
